### ISSUE TITLE
PY-T: Convert SBD to STEEM

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-py#11]
Convert SBD to STEEM

**AC**

- [x] Convert available SBD to STEEM
- [x] Explain Convert in documentation similar to JS-T

**Comment by relativityboy** [comment]
Given the status of steemit/devportal-tutorials-js#36 and the reasons for that status I'm wondering if we should mark this story as blocked and not merge the PR.

**Comment by roboza** [comment]
Blocked as per JS tutorial
