### ISSUE TITLE
PY-T: Account recovery process

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-py#3]
Account recovery process

**AC**

- [x] Account recovery code
- [x] Process of requesting recovery
- [x] Documentation similar to JS-T, if applicable

**Comment by roboza** [comment]
https://github.com/steemit/steem-python/issues/60

**Comment by relativityboy** [comment]
Interesting. According to steemit/steem-python#60 it wasn't possible a year ago with steem-python. @roboza, is that still the case? If so, do you have a proposal for next steps?

**Comment by roboza** [comment]
Can't find anything that says it will work. Still scraping the interwebs to see if anyone has mentioned anything otherwise

**Comment by roboza** [comment]
https://github.com/steemit/steem-python/commit/a29d350908825d39e6c5bdbfee068a143adb42b3

**Comment by roboza** [comment]
So I had a look again at everything including those test cases that you found.

https://github.com/steemit/steem-python/blob/master/tests/block_data/recover_account.json

From what I can gather, this is what the block data looks like for the relevant operation. The actual operation for steempython is not yet created however.

https://github.com/steemit/steem-python/blob/master/steembase/operationids.py

If you look at the operations ID's you will find that `recover_account` and `request_account_recovery` are among them, but when looking at a list of the actual created operations only the `change_recovery_account` is present. See below.

https://github.com/steemit/steem-python/blob/master/steembase/operations.py

Under the transaction tests we again only find the change account operation

https://github.com/steemit/steem-python/blob/master/tests/steem/test_transactions.py

within steemd there is also onlyl account recovery

https://github.com/steemit/steem-python/blob/master/steem/steemd.py

and under commit in steem it shows up in the "todo" list

https://github.com/steemit/steem-python/blob/master/steem/commit.py

**Comment by roboza** [comment]
I think at this point it is blocked unless we start looking at other libs?

**Comment by feruzm** [comment]
https://github.com/holgern/beem seem to have everything needed for this.

**Comment by roboza** [comment]
Investigating beem

**Comment by roboza** [comment]
Currently getting an error on beem. busy discussing with Feruz
