### ISSUE TITLE
PY-T: Grant active permission to another account (funds activity)

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-py#4]
Grant active permission to another account (funds activity)

**AC**

- [x] Grant and Revoke active permission to another account (funds activity)
- [x] Explanation about use cases
- [x] Documentation similar to JS-T

**Comment by roboza** [comment]
There is currently a bug with the `disallow` method when using it on the testnet that we normally connect to. Due to that bug, we are using the production server for this tutorial.
