### ISSUE TITLE
PY-T: HF20: Determine which tutorials are broken

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-py#79]
**AC**
- [x] In `# Results` list which tutorials are not working. Otherwise, report that all are working.

**Comment by roboza** [comment]
# Results

04 get posts – 	working
05 get post details - working
06 get voters list on post - working
07 get post comments - working
08 get account replies - working
09 get account comments - working
10 submit post – working
11 submit comment reply - working
12 edit content patching - working
13 stream blockchain transactions - working
14 reblogging post - working
15 search accounts - working
16 search tags - working
17 vote on content - working
18 follow a user - working
19 get follower and following list - working
20 account reputation - working
21 transfer steem and sbd - working
22 witness listing and voting - working
23 claim rewards - NOT working – can’t test, no rewards available on new account
24 power up steem - working
25 power down - working
27 delegate power - working
29 get delegations by user - working
30 grant posting permission - working
31 grant active permission - working
33 password key change – no account available to test on production

**Comment by relativityboy** [comment]
@roboza - this looks pretty good, except with

> 23 claim rewards - NOT working – can’t test, no rewards available on new account

I'm not sure if the tutorial itself isn't working and you've provided additional information, OR if the tutorial couldn't be gotten working because of the issues (aka will need re-evaluation later)
Can yo clarify?

**Comment by roboza** [comment]
I am going into more details.
